# requirements.yml

name: vscode_env
channels:
  - defaults
dependencies:
  - ipykernel==5.3.3
  - ipython==6.5.0
  - ipython_genutils==0.2.0
  - jupyter==1.0.0
  - jupyter_client==5.2.3
  - jupyter_console==5.2.0
  - jupyter_core==4.4.0
  - jupyterlab==0.34.9
  - jupyterlab_launcher==0.13.1
  - matplotlib==3.4.2
  - notebook==5.6.0
  - pandas==1.3.0
  - numpy==1.20.3
  - pipenv==2020.11.15
  - plotly==5.3.1
  - scikit-learn==0.23.2
  - scipy==1.6.3
  - seaborn==0.11.1
  - setuptools==41.0.1
  - torchvision>=0.2.2
  - tqdm==4.49.0
  - pytorch==1.12.1
  - wandb==0.13.5
