PATH_DATA: /home/franciscoperez/Documents/GitHub/CNN-PELSVAE/src/data
dataloader_parameters:
  batch_size: 100
  shuffle: false
  test_split: 0.0
model_parameters:
  ID: gn42liaz
  gpu: true
  sufix_path: GAIA3_LOG_IMPUTED_BY_CLASS_6PP
plotting:
  residual_plot_alpha: 0.05
  scatter_plot_alpha: 0.05
  scatter_plot_line_width: 2
regressors:
  RFR:
    criterion: mse
    max_depth: null
    max_features: null
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 200
    n_jobs: -1
save_plots: false
save_tables: false
